/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.kalki;

import com.mycompany.kalki.DBCalls.GetDBData;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author imash
 */
public class AddItem extends javax.swing.JFrame {

    /**
     * Creates new form AddItem
     */
    public AddItem() {
        initComponents();
        AutoCompleteDecorator.decorate(year);
        GetDBData bdata = new GetDBData();
        try {
            MedsName = bdata.GetAllMedsName();
            AutoCompleteDecorator.decorate(product, MedsName, false);
        } catch (Exception ex) {
            Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    ArrayList<String> MedsName = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        HSN = new javax.swing.JTextField();
        pack = new javax.swing.JTextField();
        batch = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        Sc1 = new javax.swing.JTextField();
        gst = new javax.swing.JComboBox<>();
        pts = new javax.swing.JTextField();
        month = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        sc2 = new javax.swing.JTextField();
        product = new javax.swing.JTextField();
        year = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        ptr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rate = new javax.swing.JTextField();
        mrp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("HSN *");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 120, 70, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Product *");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 77, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Pack");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(91, 161, 70, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Batch *");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(91, 210, 76, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Expiry *");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(91, 252, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("QTY *");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 340, 67, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Scheme");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 380, 60, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("GST % *");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(91, 288, 70, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("PTS *");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 460, 70, 30);

        HSN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HSN.setMaximumSize(new java.awt.Dimension(6, 23));
        HSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HSNActionPerformed(evt);
            }
        });
        getContentPane().add(HSN);
        HSN.setBounds(170, 120, 190, 30);

        pack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pack.setMaximumSize(new java.awt.Dimension(6, 23));
        getContentPane().add(pack);
        pack.setBounds(170, 160, 190, 30);

        batch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        batch.setMaximumSize(new java.awt.Dimension(6, 23));
        batch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchActionPerformed(evt);
            }
        });
        getContentPane().add(batch);
        batch.setBounds(170, 210, 190, 30);

        qty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        getContentPane().add(qty);
        qty.setBounds(170, 340, 190, 30);

        Sc1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Sc1);
        Sc1.setBounds(180, 380, 60, 30);

        gst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "18" }));
        getContentPane().add(gst);
        gst.setBounds(170, 290, 190, 40);

        pts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(pts);
        pts.setBounds(170, 460, 190, 30);

        month.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        getContentPane().add(month);
        month.setBounds(170, 250, 89, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("+");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(250, 380, 40, 30);

        sc2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(sc2);
        sc2.setBounds(280, 380, 70, 30);

        product.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        product.setMaximumSize(new java.awt.Dimension(6, 23));
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });
        getContentPane().add(product);
        product.setBounds(170, 80, 190, 30);

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", " " }));
        getContentPane().add(year);
        year.setBounds(270, 250, 90, 30);

        jButton1.setText("Add Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 600, 270, 36);

        ptr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(ptr);
        ptr.setBounds(170, 420, 190, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("PTR *");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 420, 70, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Rate *");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 500, 50, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("MRP *");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(90, 540, 50, 30);

        rate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(rate);
        rate.setBounds(170, 500, 190, 30);

        mrp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(mrp);
        mrp.setBounds(170, 540, 190, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 10, 90, 640);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(360, 10, 100, 640);

        setSize(new java.awt.Dimension(476, 694));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HSNActionPerformed

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productActionPerformed

    private void batchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String HSNCode = HSN.getText();
            String Product = product.getText();
            String Pack = pack.getText();
            String Batch = batch.getText();
            String Expire = month.getSelectedItem() + "/" + year.getSelectedItem();
            int GST = Integer.parseInt(gst.getSelectedItem().toString());
            int QTY = Integer.parseInt(qty.getText());
            String Scheme = Sc1.getText() + "+" + sc2.getText();
            Double PTS = Double.parseDouble(pts.getText());
            Double PTR = Double.parseDouble(ptr.getText());
            Double Rate = Double.parseDouble(rate.getText());
            Double MRP = Double.parseDouble(mrp.getText());
            Med med = new Med(0,HSNCode, Product, Pack, Batch, Expire, GST, QTY, Scheme, PTS, PTR, Rate, MRP);
            GetDBData dBData = new GetDBData();
            boolean result = dBData.InsertItem(med);
            if (result) {
                JOptionPane.showMessageDialog(rootPane, "Inserted Successfully");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Failed");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        HSN.setText("");
        product.setText("");
        pack.setText("");
        batch.setText("");
        qty.setText("");
        Sc1.setText("");
        sc2.setText("");
        pts.setText("");
        ptr.setText("");
        rate.setText("");
        mrp.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HSN;
    private javax.swing.JTextField Sc1;
    private javax.swing.JTextField batch;
    private javax.swing.JComboBox<String> gst;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField mrp;
    private javax.swing.JTextField pack;
    private javax.swing.JTextField product;
    private javax.swing.JTextField ptr;
    private javax.swing.JTextField pts;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField rate;
    private javax.swing.JTextField sc2;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
