/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.kalki;

import com.mycompany.kalki.DBCalls.GetDBData;
import com.mycompany.kalki.DBCalls.MongoDBCalls;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author imash
 */
public class AddItem extends javax.swing.JFrame {

    /**
     * Creates new form AddItem
     */
    public AddItem() {
        initComponents();
        AutoCompleteDecorator.decorate(year);
//        GetDBData bdata = new GetDBData();
        MongoDBCalls dbCalls = new MongoDBCalls();
        jLabel14.setVisible(false);
        try {
            MedsName = dbCalls.GetAllMedsName();
//            AutoCompleteDecorator.decorate(product, MedsName, true);

            SellerName = dbCalls.getAllSellers();
            for (int i = 0; i < SellerName.size(); i++) {
                jComboBox1.addItem(SellerName.get(i));
            }

            AutoCompleteDecorator.decorate(jComboBox1);

        } catch (Exception ex) {
            Logger.getLogger(AddItem.class.getName()).log(Level.ALL.SEVERE, null, ex);
        }
        jDateChooser1.setDate(new Date());
    }
    ArrayList<String> MedsName = new ArrayList<>();
    ArrayList<String> SellerName = new ArrayList<>();
    private static final DecimalFormat df = new DecimalFormat("0.00");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        product = new javax.swing.JTextField();
        gst = new javax.swing.JComboBox<>();
        pack = new javax.swing.JTextField();
        HSN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        batch = new javax.swing.JTextField();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        qty = new javax.swing.JTextField();
        Sc1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        sc2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ptr = new javax.swing.JTextField();
        pts = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        rate = new javax.swing.JTextField();
        mrp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Transport = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField4 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PURCHASE ENTRY");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(5, 15, 25));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Rate *");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(500, 320, 50, 30);

        product.setBackground(new java.awt.Color(5, 15, 25));
        product.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        product.setForeground(new java.awt.Color(255, 255, 255));
        product.setMaximumSize(new java.awt.Dimension(6, 23));
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });
        product.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productKeyTyped(evt);
            }
        });
        jPanel3.add(product);
        product.setBounds(200, 160, 190, 30);

        gst.setBackground(new java.awt.Color(0, 0, 0));
        gst.setEditable(true);
        gst.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gst.setForeground(new java.awt.Color(255, 255, 255));
        gst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "18" }));
        gst.setAutoscrolls(true);
        gst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gstKeyPressed(evt);
            }
        });
        jPanel3.add(gst);
        gst.setBounds(200, 360, 190, 30);

        pack.setBackground(new java.awt.Color(5, 15, 25));
        pack.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pack.setForeground(new java.awt.Color(255, 255, 255));
        pack.setMaximumSize(new java.awt.Dimension(6, 23));
        pack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                packKeyPressed(evt);
            }
        });
        jPanel3.add(pack);
        pack.setBounds(200, 240, 190, 30);

        HSN.setBackground(new java.awt.Color(5, 15, 25));
        HSN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        HSN.setForeground(new java.awt.Color(255, 255, 255));
        HSN.setMaximumSize(new java.awt.Dimension(6, 23));
        HSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HSNActionPerformed(evt);
            }
        });
        HSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HSNKeyPressed(evt);
            }
        });
        jPanel3.add(HSN);
        HSN.setBounds(200, 200, 190, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("GST % *");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(90, 370, 70, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pack *");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel3);
        jLabel3.setBounds(90, 250, 70, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel2);
        jLabel2.setBounds(500, 110, 50, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HSN *");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel1);
        jLabel1.setBounds(90, 210, 70, 30);

        jLabel13.setDisplayedMnemonic('P');
        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PURCHASE ENTRY");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(0, 10, 900, 44);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel18.setText("0.0");
        jLabel18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel18KeyReleased(evt);
            }
        });
        jPanel3.add(jLabel18);
        jLabel18.setBounds(610, 480, 190, 30);

        batch.setBackground(new java.awt.Color(5, 15, 25));
        batch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        batch.setForeground(new java.awt.Color(255, 255, 255));
        batch.setMaximumSize(new java.awt.Dimension(6, 23));
        batch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchActionPerformed(evt);
            }
        });
        batch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                batchKeyPressed(evt);
            }
        });
        jPanel3.add(batch);
        batch.setBounds(200, 280, 190, 30);

        month.setBackground(new java.awt.Color(0, 0, 0));
        month.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        month.setForeground(new java.awt.Color(255, 255, 255));
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        month.setAutoscrolls(true);
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        month.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                monthKeyPressed(evt);
            }
        });
        jPanel3.add(month);
        month.setBounds(200, 320, 89, 30);

        year.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        year.setForeground(new java.awt.Color(255, 255, 255));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", " " }));
        year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                yearKeyPressed(evt);
            }
        });
        jPanel3.add(year);
        year.setBounds(300, 320, 90, 30);

        qty.setBackground(new java.awt.Color(5, 15, 25));
        qty.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        qty.setForeground(new java.awt.Color(255, 255, 255));
        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyKeyTyped(evt);
            }
        });
        jPanel3.add(qty);
        qty.setBounds(610, 160, 190, 30);

        Sc1.setBackground(new java.awt.Color(5, 15, 25));
        Sc1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Sc1.setForeground(new java.awt.Color(255, 255, 255));
        Sc1.setText("0");
        Sc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sc1ActionPerformed(evt);
            }
        });
        Sc1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Sc1KeyPressed(evt);
            }
        });
        jPanel3.add(Sc1);
        Sc1.setBounds(610, 200, 70, 30);

        jTextField2.setBackground(new java.awt.Color(5, 15, 25));
        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(730, 360, 70, 30);

        sc2.setBackground(new java.awt.Color(5, 15, 25));
        sc2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sc2.setForeground(new java.awt.Color(255, 255, 255));
        sc2.setText("0");
        sc2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sc2KeyPressed(evt);
            }
        });
        jPanel3.add(sc2);
        sc2.setBounds(720, 200, 80, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("+");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(680, 200, 40, 30);

        jTextField1.setBackground(new java.awt.Color(5, 15, 25));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(610, 360, 60, 30);

        ptr.setBackground(new java.awt.Color(5, 15, 25));
        ptr.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ptr.setForeground(new java.awt.Color(255, 255, 255));
        ptr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ptrKeyPressed(evt);
            }
        });
        jPanel3.add(ptr);
        ptr.setBounds(610, 240, 190, 30);

        pts.setBackground(new java.awt.Color(5, 15, 25));
        pts.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pts.setForeground(new java.awt.Color(255, 255, 255));
        pts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ptsKeyPressed(evt);
            }
        });
        jPanel3.add(pts);
        pts.setBounds(610, 280, 190, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("%  =");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(670, 360, 60, 30);

        rate.setBackground(new java.awt.Color(5, 15, 25));
        rate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rate.setForeground(new java.awt.Color(255, 255, 255));
        rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rateKeyPressed(evt);
            }
        });
        jPanel3.add(rate);
        rate.setBounds(610, 320, 190, 30);

        mrp.setBackground(new java.awt.Color(5, 15, 25));
        mrp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mrp.setForeground(new java.awt.Color(255, 255, 255));
        mrp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mrpKeyPressed(evt);
            }
        });
        jPanel3.add(mrp);
        mrp.setBounds(200, 410, 190, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PTS *");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(500, 280, 70, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PTR *");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(500, 240, 70, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Scheme");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel7);
        jLabel7.setBounds(500, 200, 60, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("QTY *");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel6);
        jLabel6.setBounds(500, 160, 67, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Expiry *");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel5);
        jLabel5.setBounds(90, 330, 80, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Batch *");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel4);
        jLabel4.setBounds(90, 290, 76, 31);

        jButton1.setBackground(new java.awt.Color(255, 152, 63));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(100, 530, 710, 50);

        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(200, 70, 480, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("MRP *");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(90, 410, 50, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Invoice No: ");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel20);
        jLabel20.setBounds(90, 110, 90, 30);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Other Costs: ");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(500, 440, 170, 30);

        Transport.setBackground(new java.awt.Color(5, 15, 25));
        Transport.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Transport.setForeground(new java.awt.Color(255, 255, 255));
        Transport.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Transport.setText("0.0");
        Transport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransportActionPerformed(evt);
            }
        });
        Transport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TransportKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TransportKeyReleased(evt);
            }
        });
        jPanel3.add(Transport);
        Transport.setBounds(730, 440, 70, 30);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Product *");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel22);
        jLabel22.setBounds(90, 160, 80, 30);

        jButton2.setText("Add Seller");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(700, 70, 100, 30);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(200, 110, 190, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Seller Name: *");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel12);
        jLabel12.setBounds(90, 70, 130, 30);

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jPanel3.add(jDateChooser1);
        jDateChooser1.setBounds(610, 110, 190, 30);

        jTextField4.setBackground(new java.awt.Color(5, 15, 25));
        jTextField4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField4);
        jTextField4.setBounds(610, 400, 60, 30);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("%  =");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(670, 400, 60, 30);

        jTextField5.setBackground(new java.awt.Color(5, 15, 25));
        jTextField5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField5);
        jTextField5.setBounds(730, 400, 70, 30);

        jRadioButton1.setBackground(new java.awt.Color(5, 15, 25));
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText(" IGST Paid*");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(480, 400, 100, 30);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Total: ");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(500, 480, 70, 30);

        jRadioButton2.setBackground(new java.awt.Color(5, 15, 25));
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("GST Paid*");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(480, 360, 100, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3WyW.gif"))); // NOI18N
        jPanel3.add(jLabel14);
        jLabel14.setBounds(170, 20, 660, 680);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, -10, 920, 710);

        setSize(new java.awt.Dimension(916, 701));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HSNActionPerformed

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productActionPerformed

    private void batchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed
    private void setall(boolean b) {
        jLabel1.setVisible(b);
        jLabel2.setVisible(b);
        jLabel3.setVisible(b);
        jLabel4.setVisible(b);
        jLabel5.setVisible(b);
        jLabel6.setVisible(b);
        jLabel7.setVisible(b);
        jLabel8.setVisible(b);
        jLabel9.setVisible(b);
        jLabel10.setVisible(b);
        jLabel11.setVisible(b);
        jLabel16.setVisible(b);
        jLabel17.setVisible(b);
        jLabel18.setVisible(b);
        jLabel19.setVisible(b);
        jLabel12.setVisible(b);
        jLabel20.setVisible(b);
        jLabel2.setVisible(b);
        jLabel28.setVisible(b);
        jLabel26.setVisible(b);
        jLabel22.setVisible(b);
        jLabel23.setVisible(b);
        Transport.setVisible(b);

//        jLabel12.setVisible(b);
        product.setVisible(b);
        HSN.setVisible(b);
        pack.setVisible(b);
        batch.setVisible(b);
        qty.setVisible(b);
        Sc1.setVisible(b);
        sc2.setVisible(b);
        ptr.setVisible(b);
        pts.setVisible(b);
        rate.setVisible(b);
        mrp.setVisible(b);
        jComboBox1.setVisible(b);
        jButton2.setVisible(b);
        jTextField3.setVisible(b);
        jButton1.setVisible(b);
        month.setVisible(b);
        year.setVisible(b);
        gst.setVisible(b);
        jDateChooser1.setVisible(b);
        jRadioButton1.setVisible(b);
        jRadioButton2.setVisible(b);

        jTextField1.setVisible(b);
        jTextField2.setVisible(b);
        jTextField4.setVisible(b);
        jTextField5.setVisible(b);
    }

    public void add() {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                setall(false);
                jLabel14.setVisible(true);
            }

        });
        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                String HSNCode = HSN.getText();
                String Product = product.getText();
                String Pack = pack.getText();
                String Batch = batch.getText();
                if (HSNCode.trim().isEmpty() || Product.trim().isEmpty() || Pack.trim().isEmpty() || Batch.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "Please provide Correct Inputs");
                } else {
                    try {
                        String Expire = month.getSelectedItem() + "/" + year.getSelectedItem();
                        int GST = Integer.parseInt(gst.getSelectedItem().toString());
                        int QTY = Integer.parseInt(qty.getText());
                        String Scheme = Sc1.getText() + "+" + sc2.getText();
                        Double PTS = Double.parseDouble(pts.getText());
                        Double PTR = Double.parseDouble(ptr.getText());
                        Double Rate = Double.parseDouble(rate.getText());
                        Double MRP = Double.parseDouble(mrp.getText());
                        Double GSTPaid = Double.valueOf(jTextField1.getText());
                        Double otherCost = Double.valueOf(Transport.getText());
                        Double otherCostPerUnit=otherCost/QTY;
                        Med med = new Med(0l, HSNCode, Product, Pack, Batch, Expire, GST, QTY, Scheme, PTS, PTR, Rate+otherCostPerUnit, MRP);
//                        GetDBData dBData = new GetDBData();
                        MongoDBCalls DB = new MongoDBCalls();
                        String Company = jComboBox1.getSelectedItem().toString();
                        String AgainstInvoice = jTextField3.getText();
                        Long BillDate = jDateChooser1.getDate().getTime();
                        boolean result = DB.insertItem(med, Company, AgainstInvoice, BillDate);
                        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                        boolean presult = DB.insertPurcheseItem(med, jComboBox1.getSelectedItem().toString(),
                                jTextField3.getText(),
                                formatter.format(jDateChooser1.getDate()),
                                jTextField1.getText(),
                                jTextField4.getText(),
                                jLabel18.getText());
                        if (result && presult) {
                            JOptionPane.showMessageDialog(rootPane, "Inserted Successfully");
                            HSN.setText("");
                            product.setText("");
                            pack.setText("");
                            batch.setText("");
                            qty.setText("");
                            Sc1.setText("");
                            sc2.setText("");
                            pts.setText("");
                            ptr.setText("");
                            rate.setText("");
                            mrp.setText("");

                            jTextField1.setText("0");
                            jTextField2.setText("0");
                            jTextField4.setText("0");
                            jTextField5.setText("0");
                            jLabel18.setText("");
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Failed");
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(rootPane, "Please Provide Correct Inputs...");
                    }
                }

                setall(true);
                jLabel14.setVisible(false);

            }

        });
        t.start();
        t1.start();

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        add();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Sc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sc1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        
        double gst = Double.parseDouble(jTextField1.getText());
        Double gstamount = gst * Double.parseDouble(rate.getText()) * Double.parseDouble(qty.getText()) / 100;
        jTextField2.setText(df.format(gstamount));
        calculateTotalValue();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        System.out.println(jTextField2.getText());
        double gstamount = Double.parseDouble(jTextField2.getText());
        Double gst = gstamount * 100 / (Double.parseDouble(rate.getText()) * Double.parseDouble(qty.getText()));
        calculateTotalValue();
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void mrpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mrpKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }
    }//GEN-LAST:event_mrpKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }
    }//GEN-LAST:event_formKeyPressed

    private void productKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productKeyPressed
        product.setText(product.getText().toUpperCase());
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }
    }//GEN-LAST:event_productKeyPressed

    private void HSNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HSNKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }       // TODO add your handling code here:
    }//GEN-LAST:event_HSNKeyPressed

    private void packKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_packKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }      // TODO add your handling code here:
    }//GEN-LAST:event_packKeyPressed

    private void batchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_batchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_batchKeyPressed

    private void monthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_monthKeyPressed

    private void yearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }       // TODO add your handling code here:
    }//GEN-LAST:event_yearKeyPressed

    private void gstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gstKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }     // TODO add your handling code here:
    }//GEN-LAST:event_gstKeyPressed

    private void qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }   
        calculateTotalValue();// TODO add your handling code here:
    }//GEN-LAST:event_qtyKeyPressed

    private void Sc1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Sc1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }       // TODO add your handling code here:
    }//GEN-LAST:event_Sc1KeyPressed

    private void sc2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sc2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }       // TODO add your handling code here:
    }//GEN-LAST:event_sc2KeyPressed

    private void ptrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptrKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ptrKeyPressed

    private void ptsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ptsKeyPressed

    private void rateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rateKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }  
        calculateTotalValue();// TODO add your handling code here:
    }//GEN-LAST:event_rateKeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
        }      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddCompany company = new AddCompany();
        company.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        System.out.println(jTextField4.getText());
        double gst=Double.parseDouble(jTextField4.getText());
        Double Igstamount=gst*Double.parseDouble(rate.getText())*Double.parseDouble(qty.getText())/100;
        jTextField5.setText(df.format(Igstamount));
        calculateTotalValue();
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
      System.out.println(jTextField5.getText());
        double gstamount=Double.parseDouble(jTextField5.getText());
        Double gst=gstamount*100/(Double.parseDouble(rate.getText())*Double.parseDouble(qty.getText()));
        jTextField4.setText(gst.toString());
        calculateTotalValue();

    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jRadioButton2.setSelected(false);
        jRadioButton1.setSelected(true);
        jTextField1.setText("0");
        jTextField2.setText("0");
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField4.setEditable(true);
        jTextField5.setEditable(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(true);
        jTextField4.setText("0");
        jTextField5.setText("0");
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField1.setEditable(true);
        jTextField2.setEditable(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void productKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productKeyTyped
        product.setText(product.getText().toUpperCase());
    }//GEN-LAST:event_productKeyTyped

    private void productKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productKeyReleased
        product.setText(product.getText().toUpperCase());
    }//GEN-LAST:event_productKeyReleased

    private void TransportKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TransportKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransportKeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void TransportKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TransportKeyReleased
       calculateTotalValue();
    }//GEN-LAST:event_TransportKeyReleased

    private void jLabel18KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel18KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18KeyReleased

    private void TransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransportActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyKeyTyped

    private void calculateTotalValue(){
       
        Double GstCost = Double.valueOf(jTextField2.getText());
        Double Igstamount = Double.valueOf(jTextField5.getText());
        Double otherCost= Double.valueOf(Transport.getText());
        System.out.println(Double.parseDouble(rate.getText())* Double.parseDouble(qty.getText()));
        System.out.println(gst + " "+otherCost +" "+ Igstamount);
        Double total = (Double.parseDouble(rate.getText()) * Double.parseDouble(qty.getText())) + GstCost + otherCost + Igstamount;
        jLabel18.setText(df.format(total));
        Double sellingPrice=Double.valueOf(pts.getText());
        Double margin= (sellingPrice/total)*100;
        System.out.println(margin);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HSN;
    private javax.swing.JTextField Sc1;
    private javax.swing.JTextField Transport;
    private javax.swing.JTextField batch;
    private javax.swing.JComboBox<String> gst;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField mrp;
    private javax.swing.JTextField pack;
    private javax.swing.JTextField product;
    private javax.swing.JTextField ptr;
    private javax.swing.JTextField pts;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField rate;
    private javax.swing.JTextField sc2;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
