/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kalki;

import com.mycompany.kalki.DBCalls.MongoDBCalls;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.autocomplete.ObjectToStringConverter;

/**
 *
 * @author imash
 */
public class BillPaymentEntry extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public BillPaymentEntry() throws Exception {
        initComponents();
        jLabel14.setVisible(false);
        CustomersName = dbCalls.GetAllCustomer();
        for (int i = 0; i < CustomersName.size(); i++) {
            jComboBox1.addItem(CustomersName.get(i));
        }
        AutoCompleteDecorator.decorate(jComboBox1, ObjectToStringConverter.DEFAULT_IMPLEMENTATION);
        AutoCompleteDecorator.decorate(jComboBox2, ObjectToStringConverter.DEFAULT_IMPLEMENTATION);
    }

    public void startUp() throws Exception {
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        CustomersName.clear();
        CustomersName = dbCalls.GetAllCustomer();

        for (int i = 0; i < CustomersName.size(); i++) {
            jComboBox1.addItem(CustomersName.get(i));
        }
        AutoCompleteDecorator.decorate(jComboBox1, ObjectToStringConverter.DEFAULT_IMPLEMENTATION);
        AutoCompleteDecorator.decorate(jComboBox2, ObjectToStringConverter.DEFAULT_IMPLEMENTATION);
    }
    MongoDBCalls dbCalls = new MongoDBCalls();
    ArrayList<String> CustomersName = new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private static final DecimalFormat df = new DecimalFormat("0.00");

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(5, 15, 25));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(29, 31, 33));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Customer: ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 80, 110, 40);

        jButton2.setBackground(new java.awt.Color(255, 152, 63));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Submit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(70, 500, 450, 40);

        jLabel13.setBackground(new java.awt.Color(29, 31, 33));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Cash Entry");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(11, 23, 600, 33);

        jPanel1.setBackground(new java.awt.Color(29, 31, 33));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.white));
        jPanel1.setLayout(null);

        jLabel9.setBackground(new java.awt.Color(29, 31, 33));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("0.0");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(190, 40, 150, 40);

        jLabel10.setBackground(new java.awt.Color(29, 31, 33));
        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("0.0");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(190, 80, 150, 30);

        jLabel12.setBackground(new java.awt.Color(29, 31, 33));
        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("0.0");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(190, 160, 150, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 38, 450, 10);

        jLabel3.setBackground(new java.awt.Color(29, 31, 33));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Bill Amount: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 0, 170, 40);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 74, 450, 10);

        jLabel4.setBackground(new java.awt.Color(29, 31, 33));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FullFillment: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 120, 120, 30);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(0, 114, 450, 3);

        jLabel5.setBackground(new java.awt.Color(29, 31, 33));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amount left:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 160, 117, 40);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(0, 160, 450, 10);

        jLabel6.setBackground(new java.awt.Color(29, 31, 33));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Paid Till Date:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 35, 94, 50);

        jLabel7.setBackground(new java.awt.Color(29, 31, 33));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Amount Left Till Date:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 80, 170, 30);

        jLabel8.setBackground(new java.awt.Color(29, 31, 33));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("0.0");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 0, 150, 40);

        jTextField4.setBackground(new java.awt.Color(44, 46, 48));
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(180, 120, 170, 40);

        jLabel11.setBackground(new java.awt.Color(29, 31, 33));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Remarks:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 200, 150, 40);

        jLabel15.setBackground(new java.awt.Color(29, 31, 33));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("0.0");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(190, 200, 250, 40);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(0, 200, 450, 10);

        jLabel16.setBackground(new java.awt.Color(29, 31, 33));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Bill Date:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 240, 117, 40);

        jLabel17.setBackground(new java.awt.Color(29, 31, 33));
        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("0.0");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(190, 240, 150, 40);
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(0, 240, 450, 10);

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Full Amount");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(359, 120, 90, 40);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(70, 190, 450, 290);

        jLabel18.setBackground(new java.awt.Color(29, 31, 33));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("Bill No:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(60, 130, 110, 30);

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(150, 80, 360, 38);

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(150, 130, 360, 38);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3WyW.gif"))); // NOI18N
        jPanel2.add(jLabel14);
        jLabel14.setBounds(30, 30, 510, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setall() {

    }
    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!Utility.isNumeric(jTextField4.getText())) {
            jTextField4.setText("0");
        } else if (Double.parseDouble(jTextField4.getText()) == 0) {
            JOptionPane.showMessageDialog(rootPane, "Cannot submit Cash Entry of 0 rupees");
        } else {
            boolean cashEntry = dbCalls.CashEntry(Inv, Double.valueOf(jTextField4.getText()));
            boolean BillUpdate = dbCalls.UpdateCashPayment(Inv, Double.valueOf(jTextField4.getText()));
            try {
                try {
                    bills.clear();
                    jComboBox2.removeAllItems();
                    bills = dbCalls.GetAllBills(C_id);
                    for (int i = 0; i < bills.size(); i++) {
                        System.out.println(bills.get(i)[1].toString());
                        jComboBox2.addItem(bills.get(i)[1].toString() + " -> " + bills.get(i)[6].toString());
                    }
                } catch (Exception ex) {
                    Logger.getLogger(BillPaymentEntry.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (Exception ex) {
                Logger.getLogger(BillPaymentEntry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed
    ArrayList<Object[]> bills = new ArrayList<>();
    Long C_id = 0l;
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getItemCount() != 0) {
            C_id = Long.valueOf(jComboBox1.getSelectedItem().toString().split("=>")[1]);
            System.err.println("C_id" + C_id);
            try {
                bills.clear();
                bills = dbCalls.GetAllBills(C_id);
                for (int i = 0; i < bills.size(); i++) {
                    System.out.println(bills.get(i)[1].toString());
                    jComboBox2.addItem(bills.get(i)[1].toString() + " -> " + bills.get(i)[6].toString());
                }
            } catch (Exception ex) {
                Logger.getLogger(BillPaymentEntry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    Double NetTotal = 0.0;
    Double AmountPaid = 0.0;
    String Inv = "";
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String inv = jComboBox2.getSelectedItem().toString().split(" -> ")[0];
        Object[] data = {};
        for (int i = 0; i < bills.size(); i++) {
            System.out.println(bills.get(i)[0] + " -- " + bills.get(i)[1] + " -- " + bills.get(i)[2] + " -- " + bills.get(i)[3] + " -- " + bills.get(i)[4] + " -- " + bills.get(i)[5] + " -- " + bills.get(i)[6] + " -- " + bills.get(i)[7] + " -- " + bills.get(i)[8] + " -- " + bills.get(i)[9] + " -- ");
            if (bills.get(i)[1].toString().equals(inv)) {
                data = bills.get(i);
                break;
            }

        }
        if (data.length == 0) {
            return;
        }
        Inv = data[1].toString();
        NetTotal = (Double) data[6];
        AmountPaid = (Double) data[8];
        jLabel8.setText(df.format(data[6]));
        jLabel9.setText(df.format(data[8]));
        jLabel10.setText(df.format(NetTotal - AmountPaid));
        jLabel12.setText(df.format(NetTotal - AmountPaid));
        jLabel15.setText(data[9].toString());
        jLabel17.setText(Utility.longDateToLocalDate((Long) data[0]));


    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed

        if (Utility.isNumeric(jTextField4.getText())) {
            Double fullfillAmount = Double.parseDouble(jTextField4.getText());
            Double leftover = NetTotal - AmountPaid - fullfillAmount;
            jLabel12.setText(leftover.toString());
            if (leftover < 0) {
                jTextField4.setText(String.valueOf(NetTotal - AmountPaid));
                jLabel12.setText("0");
            }
        }

    }//GEN-LAST:event_jTextField4KeyPressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            jTextField4.setText(String.valueOf(NetTotal - AmountPaid));
            jLabel12.setText("0");
        } else {
            jTextField4.setText("0");
            jLabel12.setText(String.valueOf(NetTotal - AmountPaid));
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillPaymentEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillPaymentEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillPaymentEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillPaymentEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BillPaymentEntry().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(BillPaymentEntry.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
