/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.kalki;

import com.mycompany.kalki.DBCalls.GetDBData;
import com.mycompany.kalki.DBCalls.MongoDBCalls;
import java.sql.Date;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author imash
 */
public class SalesRecord extends javax.swing.JFrame {

    /**
     * Creates new form SalesRecoed
     */
    public SalesRecord() {
        initComponents();
        jLabel14.setVisible(false);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setTitle("Sales Record");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(5, 15, 25));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(29, 31, 33));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Starting Date :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(112, 89, 110, 30);

        jLabel2.setBackground(new java.awt.Color(29, 31, 33));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("End Date : ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(112, 130, 75, 33);

        jButton1.setBackground(new java.awt.Color(255, 152, 63));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(110, 190, 306, 42);

        jLabel13.setBackground(new java.awt.Color(29, 31, 33));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Sales Record");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(11, 23, 530, 33);

        jDateChooser1.setBackground(new java.awt.Color(29, 31, 33));
        jDateChooser1.setForeground(java.awt.Color.white);
        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(226, 89, 192, 30);

        jDateChooser2.setBackground(new java.awt.Color(29, 31, 33));
        jDateChooser2.setForeground(java.awt.Color.white);
        jDateChooser2.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(jDateChooser2);
        jDateChooser2.setBounds(226, 130, 192, 33);

        jPanel1.setBackground(new java.awt.Color(29, 31, 33));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.white));
        jPanel1.setLayout(null);

        jLabel9.setBackground(new java.awt.Color(29, 31, 33));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("0.0");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(190, 40, 150, 40);

        jLabel10.setBackground(new java.awt.Color(29, 31, 33));
        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("0.0");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(190, 80, 150, 30);

        jLabel11.setBackground(new java.awt.Color(29, 31, 33));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("0,0");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(190, 110, 150, 40);

        jLabel12.setBackground(new java.awt.Color(29, 31, 33));
        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("0,0");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(190, 150, 150, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 38, 360, 10);

        jLabel3.setBackground(new java.awt.Color(29, 31, 33));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Sales: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 2, 96, 40);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 74, 360, 10);

        jLabel4.setBackground(new java.awt.Color(29, 31, 33));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cash Collected: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 110, 114, 40);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(0, 114, 360, 20);

        jLabel5.setBackground(new java.awt.Color(29, 31, 33));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Profit: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 150, 117, 40);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(0, 150, 360, 10);

        jLabel6.setBackground(new java.awt.Color(29, 31, 33));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Taxable Amount ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 35, 153, 50);

        jLabel7.setBackground(new java.awt.Color(29, 31, 33));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total GST: ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 80, 108, 30);

        jLabel8.setBackground(new java.awt.Color(29, 31, 33));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("0.0");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 0, 150, 40);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(80, 270, 364, 202);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3WyW.gif"))); // NOI18N
        jPanel2.add(jLabel14);
        jLabel14.setBounds(31, 23, 510, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(560, 604));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void setall(boolean b) {
        jButton1.setVisible(b);
        jPanel1.setVisible(b);
        jLabel1.setVisible(b);
        jLabel2.setVisible(b);
        jDateChooser1.setVisible(b);
        jDateChooser2.setVisible(b);
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                setall(false);
                jLabel14.setVisible(true);
            }

        });
         
         Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
               long start =jDateChooser1.getDate().getTime();
        System.out.println(start);
        long End =jDateChooser2.getDate().getTime();
        ArrayList <Double> SalesDetail =new ArrayList<Double>();
            try {
                MongoDBCalls dbCalls =new MongoDBCalls();
                SalesDetail=dbCalls.GetSalesDetails(start, End);
                jLabel8.setText(SalesDetail.get(0).toString());
                jLabel9.setText(SalesDetail.get(1).toString());
                jLabel10.setText(SalesDetail.get(2).toString());
                jLabel11.setText(SalesDetail.get(3).toString());
                jLabel12.setText(SalesDetail.get(4).toString());
            } catch (Exception ex) {
                Logger.getLogger(SalesRecord.class.getName()).log(Level.SEVERE, null, ex);
            }

                setall(true);
                jLabel14.setVisible(false);

            }

        });
        t.start();
        t1.start();
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new java.awt.Color(20, 130, 59));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
         jButton1.setBackground(new java.awt.Color(255, 152, 63));
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
